# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/shreyashonnalli/Desktop/Group\ Project/GroupRepo/cpp\ codebase/OrderBookWidget/CMakeLists.txt))

/Users/shreyashonnalli/Desktop/Group\ Project/GroupRepo/cpp\ codebase/buildXcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.26.0/bin/cmake -H/Users/shreyashonnalli/Desktop/Group\ Project/GroupRepo/cpp\ codebase -B/Users/shreyashonnalli/Desktop/Group\ Project/GroupRepo/cpp\ codebase/buildXcode
