# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/shreyashonnalli/Desktop/Group\ Project/GroupRepo/cpp\ codebase/OrderBookTests/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/shreyashonnalli/Desktop/Group\ Project/GroupRepo/cpp\ codebase/buildXcode/_deps/googletest-src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/shreyashonnalli/Desktop/Group\ Project/GroupRepo/cpp\ codebase/buildXcode/_deps/googletest-src/googlemock/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/shreyashonnalli/Desktop/Group\ Project/GroupRepo/cpp\ codebase/buildXcode/_deps/googletest-src/googlemock/cmake/gmock.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/shreyashonnalli/Desktop/Group\ Project/GroupRepo/cpp\ codebase/buildXcode/_deps/googletest-src/googlemock/cmake/gmock_main.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/shreyashonnalli/Desktop/Group\ Project/GroupRepo/cpp\ codebase/buildXcode/_deps/googletest-src/googletest/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/shreyashonnalli/Desktop/Group\ Project/GroupRepo/cpp\ codebase/buildXcode/_deps/googletest-src/googletest/cmake/Config.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/shreyashonnalli/Desktop/Group\ Project/GroupRepo/cpp\ codebase/buildXcode/_deps/googletest-src/googletest/cmake/gtest.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/shreyashonnalli/Desktop/Group\ Project/GroupRepo/cpp\ codebase/buildXcode/_deps/googletest-src/googletest/cmake/gtest_main.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/shreyashonnalli/Desktop/Group\ Project/GroupRepo/cpp\ codebase/buildXcode/_deps/googletest-src/googletest/cmake/internal_utils.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.26.0/share/cmake/Modules/BasicConfigVersion-AnyNewerVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.26.0/share/cmake/Modules/CMakeDependentOption.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.26.0/share/cmake/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.26.0/share/cmake/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.26.0/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.26.0/share/cmake/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.26.0/share/cmake/Modules/FetchContent.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.26.0/share/cmake/Modules/FetchContent/CMakeLists.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.26.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.26.0/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.26.0/share/cmake/Modules/FindPython.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.26.0/share/cmake/Modules/FindPython/Support.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.26.0/share/cmake/Modules/FindSQLite3.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.26.0/share/cmake/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.26.0/share/cmake/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.26.0/share/cmake/Modules/GoogleTest.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.26.0/share/cmake/Modules/Internal/CheckSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.26.0/share/cmake/Modules/WriteBasicConfigVersionFile.cmake))

/Users/shreyashonnalli/Desktop/Group\ Project/GroupRepo/cpp\ codebase/buildXcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.26.0/bin/cmake -H/Users/shreyashonnalli/Desktop/Group\ Project/GroupRepo/cpp\ codebase -B/Users/shreyashonnalli/Desktop/Group\ Project/GroupRepo/cpp\ codebase/buildXcode
